version: '3.8'
services:
  payload:
    build: .
    env_file:
      - .env
    environment:
      PAYLOAD_SECRET: ${PAYLOAD_SECRET}
      DATABASE_URI: ${DATABASE_URI}
      S3_ENDPOINT: ${S3_ENDPOINT}
      PORT: ${PORT}
      TRUST_PROXY: ${TRUST_PROXY}
    ports:
      - "${PORT}:3000"
    depends_on:
      - db
      - minio
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SITE_NAME}.rule=Host(`${SITE_DOMAIN}`)"
      - "traefik.http.routers.${SITE_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${SITE_NAME}.tls.certresolver=lets-encrypt"
    networks:
      - web
      - internal

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: payload
      POSTGRES_USER: payload
      POSTGRES_PASSWORD: payload
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio_data:/data
    networks:
      - internal

networks:
  web:
    external: true
  internal:
    driver: bridge

volumes:
  pgdata:
  minio_data:
